In [1]:
import time
import akshare as ak
import pandas as pd
import numpy as np
import tqdm
# import pyecharts.options as opts
# from pyecharts.charts import Line
import tqdm
import pandas as pd
from sqlalchemy import create_engine
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
import pymysql
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")
conn = pymysql.connect(
            host='127.0.0.1',
            user='root',
            password='chen',
            database='gp',
            # use_unicode=args.encoding,
        )
cursor = conn.cursor()
def toSql(sql: str, rows: list):
    """
        连接数据库
    """
    # print(sql,rows)
    try:

        cursor.executemany(sql, rows)
        conn.commit()
    except Exception as e:
        raise ConnectionError("[ERROR] 连接数据库失败，具体原因是：" + str(e))

c:\Users\cyw\.conda\envs\stock\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
C:\Users\cyw\AppData\Roaming\Python\Python310\site-packages\py_mini_racer\py_mini_racer.py:15: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

### 分歧因子
a=((rank(max((Vwap-close),3))+rank(min((Vwap-close),3))) * rank(delta(volume,3)))

In [3]:
sql = """
SELECT date, code, close, volume, amount
FROM stock
WHERE volume IS NOT NULL
ORDER BY code, date
"""

df = pd.read_sql(sql, engine)

计算 VWAP + diff

In [ ]:
# 去掉停牌 / 无量
df = df[df['volume'] > 0]
df = df[df['amount'] > 5000]  # 自己调
df['vwap'] = df['amount'] / df['volume']
df['diff'] = df['vwap'] - df['close']
# 过滤异常值（强烈建议）
df['diff'] = df['diff'].clip(-0.1, 0.1)

按股票计算 rolling（关键）

In [5]:
df = df.sort_values(['code', 'date'])

# 3日最大最小
df['max3'] = df.groupby('code')['diff'].rolling(3).max().reset_index(level=0, drop=True)
df['min3'] = df.groupby('code')['diff'].rolling(3).min().reset_index(level=0, drop=True)

# 3日成交量变化
df['delta_vol'] = df.groupby('code')['volume'].diff(3)

横截面 rank（核心）

In [6]:
# 每天做排名（0~1）
df['rank_max3'] = df.groupby('date')['max3'].rank(pct=True)
df['rank_min3'] = df.groupby('date')['min3'].rank(pct=True)
df['rank_vol'] = df.groupby('date')['delta_vol'].rank(pct=True)

最终因子

In [7]:
df['alpha'] = (df['rank_max3'] + df['rank_min3']) * df['rank_vol']

In [10]:
top_n = df.sort_values(['date', 'alpha'], ascending=[True, False]) \
          .groupby('date') \
          .head(10)

In [12]:
top_n.tail()

,date,code,close,volume,amount,vwap,diff,max3,min3,delta_vol,rank_max3,rank_min3,rank_vol,alpha
236405,2026-04-21,sh601166,18.42,105943311.0,1.961763e+09,18.517105,0.097105,0.097105,0.030892,50081328.0,0.750170,0.980050,0.975323,1.687523
894138,2026-04-21,sz002962,18.10,44475920.0,8.098658e+08,18.209086,0.109086,0.234596,0.021965,12565479.0,0.879166,0.975062,0.896536,1.662382
714119,2026-04-21,sz002272,19.33,83692783.0,1.623644e+09,19.400051,0.070051,0.181905,0.070051,12194971.0,0.844933,0.988438,0.894725,1.640363
278800,2026-04-21,sh601933,3.88,169980209.0,6.651256e+08,3.912959,0.032959,0.088176,0.030869,29841805.0,0.735207,0.979823,0.953588,1.635433
1161838,2026-04-21,sz300919,57.65,25031153.0,1.453563e+09,58.070167,0.420167,0.420167,0.209479,6711826.0,0.937429,0.995693,0.845370,1.634203

In [24]:
ls=['sz003027','sz002039','sh603196','sh603278','sz002081','sz301667','sh603178','sz002338','sz002853','sh600736','sz301099','sh600522','sz301486','sz002536','sh600118','sh600301','sh600208','sz001330','sz000880']
# ls=["sh603130","sz002203","sh603318","sz002487","sh600433","sh600552","sz301548","sh603906","sh600520","sh600206","sz002119","sz301603","sz300373","sz002885","sh601002","sz300351","sz300696","sz002498","sh600156","sh605388","sz000062","sh600601","sz300617","sz300063","sz002899","sh600234","sh603322","sz300364","sz300785","sh603598","sz300249","sz301171"]
df.loc[(df['date'].astype(str)=='2026-04-21')&(df['code'].isin(ls))].sort_values('alpha',ascending=False)

,date,code,close,volume,amount,vwap,diff,max3,min3,delta_vol,rank_max3,rank_min3,rank_vol,alpha
784152,2026-04-21,sz002536,38.50,108637893.0,4.273768e+09,39.339566,0.839566,0.839566,-1.550690,67519514.0,0.975062,0.028112,0.985511,0.988638
1288310,2026-04-21,sz301486,209.06,21243849.0,4.143579e+09,195.048427,-14.011573,1.826367,-14.011573,15650018.0,0.992972,0.000453,0.913290,0.907285
731572,2026-04-21,sz002338,64.06,23997255.0,1.493645e+09,62.242328,-1.817672,0.584505,-1.817672,17651773.0,0.959420,0.022897,0.921440,0.905146
333736,2026-04-21,sh603196,33.10,9175277.0,3.010251e+08,32.808285,-0.291715,0.488069,-0.291715,3777917.0,0.947178,0.188619,0.788091,0.895112
63772,2026-04-21,sh600301,54.98,21158800.0,1.137096e+09,53.741028,-1.238972,0.728396,-1.238972,10219240.0,0.969168,0.039900,0.881141,0.889131
585473,2026-04-21,sz000880,31.58,50419505.0,1.596165e+09,31.657681,0.077681,0.077681,-0.608166,34841728.0,0.712764,0.095217,0.961739,0.777066
1314027,2026-04-21,sz301667,115.90,12305964.0,1.331868e+09,108.229504,-7.670496,0.306145,-7.670496,5485199.0,0.908411,0.002494,0.821372,0.748191
45117,2026-04-21,sh600208,3.90,286459439.0,1.096630e+09,3.828222,-0.071778,-0.033110,-0.107390,241594512.0,0.094763,0.420313,0.997510,0.513793
1211172,2026-04-21,sz301099,59.93,15732052.0,8.973426e+08,57.039134,-2.890866,0.019608,-2.890866,10047738.0,0.449785,0.012015,0.880235,0.406493
160577,2026-04-21,sh600736,6.92,49452784.0,3.328656e+08,6.730977,-0.189023,-0.026684,-0.189023,37027167.0,0.106325,0.284289,0.964003,0.376553
661831,2026-04-21,sz002081,4.49,119557510.0,5.310113e+08,4.441472,-0.048528,-0.028300,-0.214514,101569440.0,0.102471,0.259578,0.990718,0.358689
630625,2026-04-21,sz001330,8.83,222407784.0,1.960889e+09,8.816637,-0.013363,-0.010672,-0.407011,125476184.0,0.163002,0.142371,0.992982,0.303230
651006,2026-04-21,sz002039,22.00,26225263.0,5.629548e+08,21.466126,-0.533874,-0.022267,-0.533874,14676772.0,0.116754,0.109499,0.907630,0.205354
350946,2026-04-21,sh603278,13.24,67730867.0,8.903298e+08,13.145112,-0.094888,-0.094888,-0.405839,62322957.0,0.037180,0.142598,0.983699,0.176847
911877,2026-04-21,sz003027,25.15,12118730.0,2.966030e+08,24.474757,-0.675243,-0.036292,-0.675243,6005380.0,0.089095,0.086375,0.832692,0.146113
864963,2026-04-21,sz002853,29.03,5411740.0,1.529964e+08,28.271197,-0.758803,-0.026394,-0.758803,2690040.0,0.107005,0.073906,0.755037,0.136595
109777,2026-04-21,sh600522,32.44,395727458.0,1.254054e+10,31.689848,-0.750152,-0.123697,-0.750152,266906649.0,0.028565,0.075493,0.998415,0.103893
328621,2026-04-21,sh603178,21.08,27955239.0,5.567899e+08,19.917192,-1.162808,-0.109288,-1.162808,24843211.0,0.032419,0.043528,0.942721,0.071596
25587,2026-04-21,sh600118,100.20,119231962.0,1.178876e+10,98.872481,-1.327519,-0.397669,-2.867008,74670661.0,0.007255,0.012469,0.987775,0.019482

In [23]:
df.loc[(df['code'].isin(['sh600480']))].sort_values('date',ascending=False)

,date,code,close,volume,amount,vwap,diff,max3,min3,delta_vol,rank_max3,rank_min3,rank_vol,alpha
98959,2026-04-21,sh600480,10.70,63564243.0,6.898924e+08,10.853467,0.153467,0.153467,-0.122511,3718584.0,0.821129,0.380639,0.786280,0.944927
98958,2026-04-20,sh600480,11.36,42358448.0,4.831363e+08,11.405901,0.045901,0.045901,-0.122511,-13473507.0,0.680870,0.436310,0.087409,0.097652
98957,2026-04-17,sh600480,11.54,38320161.0,4.375200e+08,11.417489,-0.122511,-0.096627,-0.122511,-37775959.0,0.014276,0.410605,0.024683,0.010487
98956,2026-04-16,sh600480,11.59,59845659.0,6.878285e+08,11.493373,-0.096627,0.052660,-0.118843,-46072055.0,0.438251,0.467482,0.021971,0.019899
98955,2026-04-15,sh600480,11.72,55831955.0,6.477153e+08,11.601157,-0.118843,0.052660,-0.165690,-7663719.0,0.413418,0.306210,0.125481,0.090300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98663,2025-01-24,sh600480,10.09,66344362.0,8.681412e+08,13.085380,2.995380,3.335165,2.995380,27492025.0,0.972738,0.974835,0.958034,1.865841
98662,2025-01-23,sh600480,9.48,68424158.0,8.768669e+08,12.815165,3.335165,3.335165,2.875527,54173278.0,0.972738,0.971839,0.968235,1.882808
98661,2025-01-22,sh600480,9.63,98468491.0,1.245764e+09,12.651396,3.021396,3.021396,0.092408,NaN,0.967568,0.833033,NaN,NaN
98660,2025-01-21,sh600480,8.95,38852337.0,4.594494e+08,11.825527,2.875527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98659,2020-01-29,sh600480,11.70,14250880.0,1.680522e+08,11.792408,0.092408,NaN,NaN,NaN,NaN,NaN,NaN,NaN