In [1]:
import baostock as bs
import pandas as pd
import tqdm
from datetime import datetime
from dateutil.relativedelta import relativedelta
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")

In [2]:
sql="""SELECT aly.*,stock.outstanding_share  FROM gp.stock_analysis as aly
join (select code,max(outstanding_share) as outstanding_share from gp.stock s 
	where outstanding_share !=0 group by code  ) as stock
	on stock.code =aly.stock_code 
WHERE need_to_analysis = 1"""
need_analysis_df=pd.read_sql(sql=sql,con=engine)

In [3]:
today_dt = datetime.today().replace(hour=0, minute=0, second=0, microsecond=0)
today_str = today_dt.strftime("%Y-%m-%d")
one_year_ago = today_dt - relativedelta(years=1)

start_date = one_year_ago.strftime("%Y-%m-%d")

In [9]:
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)
res_df_list=[]
for k,v in tqdm.tqdm(need_analysis_df.iterrows()):
    code=v['stock_code'][0:2]+'.'+v['stock_code'][2:]
    rs = bs.query_history_k_data_plus(code,
        "date,time,code,open,high,low,close,volume,amount,adjustflag",
        start_date=start_date, end_date=today_str,
        frequency="5", adjustflag="3")

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    results = pd.DataFrame(data_list, columns=rs.fields)
    results['code']=v['stock_code']
    results['ltgb']=v['outstanding_share']
    res_df_list.append(results)
result=pd.concat(res_df_list)
#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success

2it [00:47, 23.97s/it]

logout success!

In [15]:
df=result
# df['time']=df['time'].map(lambda x:x[:12])
df['time']=pd.to_datetime(df['time'],format="%Y%m%d%H%M%S%f")
df['hour']=df['time'].dt.hour
df['minute']=df['time'].dt.minute

df['pre_close']=df['close'].shift(1)
df=df.loc[df['date']!=start_date]

res_df = []
for date, v in tqdm.tqdm(df.groupby(['code','date'])):
    # 1. 计算当天最高价 (这是标量，没问题)
    today_high = v['high'].max()
    # 2. 提取特定时间的数据，并强制转换为标量 (使用 .iloc[0])
    # 添加简单的错误处理，防止某天缺少开盘或收盘数据
    
    # 提取开盘 (09:35)
    open_series = v.loc[(v['hour']==9) & (v['minute']==35), 'open']
    if open_series.empty:
        continue # 或者设为 np.nan
    today_open = open_series.iloc[0]
    
    # 提取收盘 (15:00)
    close_series = v.loc[(v['hour']==15) & (v['minute']==0), 'close']
    if close_series.empty:
        continue
    today_close = close_series.iloc[0]
    
    # 提取昨收 (09:35 的 pre_close)
    yes_close_series = v.loc[(v['hour']==9) & (v['minute']==35), 'pre_close']
    if yes_close_series.empty:
        continue
    yes_close = yes_close_series.iloc[0]
    
    # 3. 确保是浮点数进行计算
    today_open = float(today_open)
    today_close = float(today_close)
    yes_close = float(yes_close)
    
    # 4. 计算涨幅 (此时都是数字，不会报错)
    # 防止除以0
    if yes_close != 0:
        zf = round((today_close - yes_close) / yes_close, 2)
    else:
        zf = 0.0
        
    if today_open != 0:
        sjzf = round((today_close - today_open) / today_open, 2)
    else:
        sjzf = 0.0
    
    # 5. 赋值给新列
    # 因为今天是标量 (scalar)，Pandas 会自动广播到该组的所有行
    v['today_high'] = today_high   # 修正了变量名拼写 hight -> high
    v['today_open'] = today_open
    v['today_close'] = today_close
    v['yes_close'] = yes_close
    v['zf'] = zf
    v['sjzf'] = sjzf
    v=v.iloc[0:3]
    res_df.append(v)

# 合并数据
if res_df:
    dfs = pd.concat(res_df, ignore_index=False) # 保持原有索引或重置
    print("处理完成，前5行数据：")
    # print(dfs.head())
else:
    print("未生成任何数据，请检查时间筛选条件是否匹配。")

100%|██████████| 483/483 [00:01<00:00, 449.00it/s]

处理完成，前5行数据：

In [16]:
def estimate_bar_buy_ratio(row):
    high = row['high']
    low = row['low']
    close = row['close']
    
    # 处理可能的缺失值 (NaN)
    if pd.isna(high) or pd.isna(low) or pd.isna(close):
        return np.nan
    range_val = high - low
    # print(range_val)
    if range_val == 0:
        return 0.5 # 无波动视为中性
    
    ratio = (close - low) / range_val
    return round(ratio,2)

dfs['high']=dfs['high'].astype(float)
dfs['low']=dfs['low'].astype(float)
dfs['close']=dfs['close'].astype(float)
dfs['buy_ratio']=dfs.apply(estimate_bar_buy_ratio,axis=1)
dfs['volume']=dfs['volume'].astype(int)
dfs['est_buy_vol'] = dfs['volume'] * dfs['buy_ratio']
dfs['est_sell_vol'] = dfs['volume'] * (1 - dfs['buy_ratio'])

In [17]:
min15_df=[]
for k,v in dfs.groupby(['code','date']):
    buy_volume=v['est_buy_vol'].sum()
    sell_volume=v['est_sell_vol'].sum()
    # if sell_volume==0:
    #     buy_ratio=-1
    # else:
    #     buy_ratio=buy_volume/sell_volume

    buy_ratio=(buy_volume+1e-8)/(sell_volume+1e-8)
    # if buy_ratio>50:
    #     buy_ratio=50
    all_volume=buy_volume+sell_volume
    all_lt_volume=v.iloc[0]['ltgb']
    zb=round(all_volume/all_lt_volume,4)
    v.reset_index(drop=True,inplace=True)
    zf=v.loc[0,'zf']
    sjzf=v.loc[0,'sjzf']
    dt={
        "buy_volume":buy_volume,
        "sell_volume":sell_volume,
        "buy_ratio":buy_ratio,
        "all_volume":all_volume,
        "zb":zb,
        "zf":zf,
        "sjzf":sjzf,
        "date":k[1],
        'code':k[0]
    }
    min15_df.append(dt)
min15_df=pd.DataFrame(min15_df)
min15_df['next_day_zf']=min15_df['zf'].shift(-1)

In [ ]:
min_buy_ratio=min15_df.loc[min15_df['code']=='sh600726']['buy_ratio'].min()
max_buy_ratio=min15_df.loc[min15_df['code']=='sh600726']['buy_ratio'].max()
print(min_buy_ratio,max_buy_ratio)

1.4971404617181162e-15 352950000000001.0

In [25]:
min15_df

,buy_volume,sell_volume,buy_ratio,all_volume,zb,zf,sjzf,date,code,next_day_zf
0,4629550.0,482850.0,9.587967e+00,5112400.0,0.0007,0.02,0.03,2025-03-25,sh600726,-0.01
1,1893800.0,5595200.0,3.384687e-01,7489000.0,0.0010,-0.01,-0.01,2025-03-26,sh600726,-0.02
2,0.0,5556200.0,1.799791e-15,5556200.0,0.0007,-0.02,-0.01,2025-03-27,sh600726,-0.01
3,2151050.0,821050.0,2.619877e+00,2972100.0,0.0004,-0.01,-0.01,2025-03-28,sh600726,0.00
4,1766550.0,4146450.0,4.260391e-01,5913000.0,0.0008,0.00,0.00,2025-03-31,sh600726,0.02
...,...,...,...,...,...,...,...,...,...,...
478,165281.0,41019.0,4.029377e+00,206300.0,0.0015,0.06,0.05,2026-03-18,sh605389,0.10
479,945575.8,170144.2,5.557497e+00,1115720.0,0.0082,0.10,0.10,2026-03-19,sh605389,0.01
480,433915.8,266044.2,1.630991e+00,699960.0,0.0051,0.01,0.01,2026-03-20,sh605389,-0.05
481,344888.0,282292.0,1.221742e+00,627180.0,0.0046,-0.05,-0.05,2026-03-23,sh605389,-0.01
482,35325.0,265275.0,1.331637e-01,300600.0,0.0022,-0.01,-0.04,2026-03-24,sh605389,NaN

In [26]:
min_buy_ratio=min15_df.loc[min15_df['code']=='sh605389']['buy_ratio'].min()
max_buy_ratio=min15_df.loc[min15_df['code']=='sh605389']['buy_ratio'].max()
print(min_buy_ratio,max_buy_ratio)

0.035455236073437424 109.58873358741172

In [28]:
for k,v in tqdm.tqdm(min15_df.groupby('code')):
    min_buy_ratio=v['buy_ratio'].min()
    max_buy_ratio=v['buy_ratio'].max()
    min_zb=v['zb'].min()
    max_zb=v['zb'].max()
    need_analysis_df.loc[need_analysis_df['stock_code']==k,'min_buy_ratio']=min_buy_ratio
    need_analysis_df.loc[need_analysis_df['stock_code']==k,'max_buy_ratio']=max_buy_ratio
    need_analysis_df.loc[need_analysis_df['stock_code']==k,'min_zb']=min_zb
    need_analysis_df.loc[need_analysis_df['stock_code']==k,'max_zb']=max_zb

100%|██████████| 2/2 [00:00<00:00, 486.41it/s]

In [20]:
need_analysis_df.columns

Index(['stock_code', 'stock_name', 'need_to_analysis', 'trigger_count',
       'is_abnormal_type', 'warning_info', 'industry_block', 'concept_block',
       'region_block', 'concept_block_resonance', 'create_time', 'update_time',
       'outstanding_share', 'min_buy_ratio', 'max_buy_ratio', 'min_zb',
       'max_zb'],
      dtype='object')

In [ ]:
need_analysis_df=need_analysis_df[['stock_code', 'stock_name', 'need_to_analysis', 'trigger_count',
       'is_abnormal_type', 'warning_info', 'industry_block', 'concept_block',
       'region_block', 'concept_block_resonance','min_buy_ratio', 'max_buy_ratio', 'min_zb',
       'max_zb']]

In [29]:
need_analysis_df

,stock_code,stock_name,need_to_analysis,trigger_count,is_abnormal_type,warning_info,industry_block,concept_block,region_block,concept_block_resonance,create_time,update_time,outstanding_share,min_buy_ratio,max_buy_ratio,min_zb,max_zb
0,sh600726,华电能源,1,1,30日涨跌幅异常(116.47%),None,电力(1.46),超临界发电(0.00)，绿色电力(-0.06),黑龙江(1.11),0.69,2026-03-20 16:44:16,2026-03-20 16:44:16,7.475336e+09,1.497140e-15,3.529500e+14,0.0002,0.0329
1,sh605389,长龄液压,1,1,None,明日若涨 7.55% 将触发3日异动,工程机械(-2.18),机器人概念(-1.29)，高端装备(-1.40),江苏板块(-0.78),0.48,2026-03-20 16:44:16,2026-03-20 16:44:16,1.362668e+08,3.545524e-02,1.095887e+02,0.0000,0.0414

In [183]:
import akshare as ak
stock_code='sz000539'
dfx = ak.stock_zh_a_tick_tx_js(symbol=stock_code)

c:\Users\cyw\.conda\envs\stock\lib\site-packages\akshare\stock\stock_zh_a_tick_tx.py:27: UserWarning: 正在下载数据，请稍等
  warnings.warn("正在下载数据，请稍等")

In [184]:
dft=dfx

In [201]:
dft.to_excel(r'C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\sz000539.xlsx')

In [185]:
dft['成交时间']=pd.to_datetime(dft['成交时间'])
dft['hour']=dft['成交时间'].dt.hour
dft['mintue']=dft['成交时间'].dt.minute
dft['成交量']=dft['成交量']*100

C:\Users\cyw\AppData\Local\Temp\ipykernel_35244\1879835045.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dft['成交时间']=pd.to_datetime(dft['成交时间'])

In [188]:
if '成交时间' in dft.columns:
    dft['成交时间'] = pd.to_datetime(dft['成交时间'])
    dft.set_index('成交时间', inplace=True)
    dft.sort_index(inplace=True)

dft['raw_type'] = dft['性质'].astype(str)
dft['type_code'] = 0
dft.loc[dft['raw_type'].str.contains('买', na=False), 'type_code'] = 1
dft.loc[dft['raw_type'].str.contains('卖', na=False), 'type_code'] = -1

if 'price_shift' not in dft.columns:
    dft['price_shift'] = dft['成交价格'].shift(-1) - dft['成交价格']
neutral_mask = (dft['type_code'] == 0)
dft.loc[neutral_mask & (dft['price_shift'] > 0), 'type_code'] = 1
dft.loc[neutral_mask & (dft['price_shift'] < 0), 'type_code'] = -1
dft=dft.loc[(dft['hour']==9)&(dft['mintue']>=0)&(dft['mintue']<=45)]

C:\Users\cyw\AppData\Local\Temp\ipykernel_35244\2868145823.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dft['raw_type'] = dft['性质'].astype(str)
C:\Users\cyw\AppData\Local\Temp\ipykernel_35244\2868145823.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dft['type_code'] = 0

In [189]:
dft.tail()

,成交价格,价格变动,成交量,成交金额,性质,hour,mintue,raw_type,type_code,price_shift
成交时间,,,,,,,,,,
2026-03-25 09:45:45,7.24,0.0,106700,772134,买盘,9,45,买盘,1,0.00
2026-03-25 09:45:48,7.24,0.0,110000,796301,买盘,9,45,买盘,1,0.00
2026-03-25 09:45:51,7.24,0.0,30400,220137,卖盘,9,45,卖盘,-1,0.00
2026-03-25 09:45:54,7.24,0.0,174100,1261652,卖盘,9,45,卖盘,-1,0.00
2026-03-25 09:45:57,7.24,0.0,120300,871588,卖盘,9,45,卖盘,-1,0.01

In [190]:
pivot_df=pd.pivot_table(
    dft,
    index='mintue',
    columns='性质',
    values='成交量',
    aggfunc='sum',
    fill_value=0
)

In [191]:
pivot_df['总计']=pivot_df['买盘']+pivot_df['卖盘']

In [192]:
# 3. 计算累计值 (核心步骤)
# cumsum() 会沿着索引顺序（这里是分钟从小到大）进行累加
pivot_df['累计_买盘'] = pivot_df['买盘'].cumsum()
pivot_df['累计_卖盘'] = pivot_df['卖盘'].cumsum()
pivot_df['累计_总计'] = pivot_df['总计'].cumsum()

In [193]:
df_al=pd.read_sql(f"select * from gp.stock_analysis where stock_code='{stock_code}'",con=engine)

In [194]:
pivot_df['max_buy_ratio']=df_al['max_buy_ratio'].to_list()[0]
pivot_df['min_buy_ratio']=df_al['min_buy_ratio'].to_list()[0]
pivot_df['max_zb']=df_al['max_zb'].to_list()[0]
pivot_df['min_zb']=df_al['min_zb'].to_list()[0]
pivot_df['stock_code']=df_al['stock_code'].to_list()[0]
pivot_df['stock_name']=df_al['stock_name'].to_list()[0]

In [195]:
pivot_df['buy_ratio']=pivot_df['累计_买盘']/pivot_df['累计_卖盘']

In [196]:
pivot_df['buy_ratio_norm'] = (pivot_df['buy_ratio'] - pivot_df['min_buy_ratio']) / (pivot_df['max_buy_ratio'] - pivot_df['min_buy_ratio'])

In [197]:
pivot_df=pivot_df.reset_index()

In [198]:
pivot_df

性质,mintue,中性盘,买盘,卖盘,总计,累计_买盘,累计_卖盘,累计_总计,max_buy_ratio,min_buy_ratio,max_zb,min_zb,stock_code,stock_name,buy_ratio,buy_ratio_norm
0,25,0,8684600,0,8684600,8684600,0,8684600,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,inf,inf
1,30,0,3692500,22321200,26013700,12377100,22321200,34698300,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.554500,0.010932
2,31,694000,9690800,7831200,17522000,22067900,30152400,52220300,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.731879,0.015124
3,32,1917600,3928700,5726600,9655300,25996600,35879000,61875600,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.724563,0.014951
4,33,0,4884200,4071200,8955400,30880800,39950200,70831000,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.772982,0.016096
5,34,0,2385800,4310400,6696200,33266600,44260600,77527200,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.751608,0.015591
6,35,163600,5024500,62000,5086500,38291100,44322600,82613700,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.863918,0.018245
7,36,0,3309200,5522500,8831700,41600300,49845100,91445400,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.834592,0.017552
8,37,0,6262000,3223600,9485600,47862300,53068700,100931000,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.901893,0.019142
9,38,0,2246100,5250400,7496500,50108400,58319100,108427500,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.859211,0.018134
10,39,0,1901400,2149000,4050400,52009800,60468100,112477900,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.860120,0.018155
11,40,130000,2088300,1041300,3129600,54098100,61509400,115607500,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.879509,0.018613
12,41,271400,3054200,2635400,5689600,57152300,64144800,121297100,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.890989,0.018885
13,42,143900,1470700,2188100,3658800,58623000,66332900,124955900,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.883770,0.018714
14,43,94000,1874100,794800,2668900,60497100,67127700,127624800,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.901224,0.019126
15,44,40700,290200,1393900,1684100,60787300,68521600,129308900,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.887126,0.018793
16,45,0,1957600,972400,2930000,62744900,69494000,132238900,42.4064,0.0919,0.0552,0.0003,sz000539,粤电力Ａ,0.902882,0.019166

In [199]:
from pyecharts.charts import Line
from pyecharts import options as opts
import pandas as pd
import numpy as np

def plot_buy_ratio_line(df):
    # ========= 1. 数据清洗 =========
    df = df.copy()

    # 处理 inf
    df['buy_ratio_norm'] = np.where(
        np.isfinite(df['buy_ratio_norm']),
        df['buy_ratio_norm'],
        0
    )

    # minute 转 int（避免排序问题）
    df['mintue'] = df['mintue'].astype(int)

    # ========= 2. 获取所有股票 =========
    stock_list = df['stock_name'].unique().tolist()

    # ========= 3. 初始化图 =========
    line = Line()

    # X轴统一（取全集）
    x_axis = sorted(df['mintue'].astype(str).unique().tolist())
    line.add_xaxis(x_axis)
    # print(x_axis)
    # ========= 4. 循环每个股票 =========
    for stock in stock_list:
        tmp = df[df['stock_name'] == stock].sort_values('mintue')
        
        # 对齐分钟（防止缺失）
        y_axis=tmp['buy_ratio_norm'].round(3).tolist()
        print(y_axis)
        line.add_yaxis(
            series_name=stock,
            y_axis=y_axis,
            is_smooth=True,
            label_opts=opts.LabelOpts(is_show=False),
        )

    # ========= 5. 全局配置 =========
    line.set_global_opts(
        title_opts=opts.TitleOpts(title="分时买卖强度 (buy_ratio_norm)"),
        tooltip_opts=opts.TooltipOpts(trigger="axis"),
        xaxis_opts=opts.AxisOpts(name="分钟"),
        # yaxis_opts=opts.AxisOpts(name="买卖比(归一化)",min_=0,max_=0.02),
        legend_opts=opts.LegendOpts(pos_top="5%"),
        datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")]
    )

    return line


# ===== 使用示例 =====
# line = plot_buy_ratio_line(df)
# line.render("buy_ratio_line.html")
chart = plot_buy_ratio_line(pivot_df)
chart.render(r"C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\multi_stock_monitor_fixed.html")

[0.0, 0.011, 0.015, 0.015, 0.016, 0.016, 0.018, 0.018, 0.019, 0.018, 0.018, 0.019, 0.019, 0.019, 0.019, 0.019, 0.019]

'C:\\Users\\cyw\\Desktop\\jupyternotebook\\git-python\\GP\\当日策列\\static\\multi_stock_monitor_fixed.html'

In [202]:
basic_df = ak.stock_zh_a_daily(
            symbol='sh600191',
            start_date='20250325',
            end_date='20260325',
            adjust="qfq"
        ).sort_values(by='date')

In [203]:
basic_df

,date,open,high,low,close,volume,amount,outstanding_share,turnover
0,2025-03-25,7.04,7.04,6.88,7.00,5370660.0,37404106.0,484932000.0,0.011075
1,2025-03-26,7.00,7.12,6.96,7.09,4938960.0,34916896.0,484932000.0,0.010185
2,2025-03-27,7.05,7.16,7.00,7.11,4832100.0,34316108.0,484932000.0,0.009964
3,2025-03-28,7.12,7.13,6.92,6.96,8297400.0,58234656.0,484932000.0,0.017110
4,2025-03-31,6.95,7.35,6.85,7.30,14720501.0,105722471.0,484932000.0,0.030356
...,...,...,...,...,...,...,...,...,...
236,2026-03-18,12.32,12.59,12.02,12.11,6329923.0,77102714.0,484932000.0,0.013053
237,2026-03-19,12.10,12.50,11.98,12.30,5811684.0,70625032.0,484932000.0,0.011985
238,2026-03-20,12.18,12.29,11.75,11.98,5664500.0,68336115.0,484932000.0,0.011681
239,2026-03-23,11.87,11.87,11.21,11.21,9594700.0,110072497.0,484932000.0,0.019786
240,2026-03-24,11.43,11.49,10.31,10.89,16795360.0,180694863.0,484932000.0,0.034634